name: Update Packagist

on:
  push:
    tags:
      - '*'

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Packagist
        uses: mnavarrocarter/packagist-update@v1.0
        with:
          username: "eliseusantos"
          api_token: ${{ secrets.PACKAGIST_TOKEN }}
          package_name: vendor/laravel-contaazul
          domain: "packagist.org"
